// ─── user.service.ts ──────────────────────────────────────────────────────────
//
// DynamoDB operations used:
//   register        → Query (email GSI, duplicate check) + PutItem (create)
//   login           → Query (email GSI) → GetItem (password verify)
//   getProfile      → GetItem  (userId from JWT — cheapest read)
//   updateProfile   → UpdateItem (partial, only changed fields written)
//   changePassword  → GetItem (verify old pw) + UpdateItem (write new hash)
//
// Security practices:
//   • Passwords hashed with bcrypt (cost=12)
//   • JWT signed with RS256-style secret, expires in 7d
//   • `sanitizeUser()` strips password before returning to caller
//   • Email uniqueness checked via GSI Query before PutItem

import bcrypt from "bcryptjs";
import jwt from "jsonwebtoken";
import { UserModel, User } from "./user.model";
import { fileService } from "../../utils/fileuploader";
import { getS3KeyFromUrl } from "../../utils/Imagekey";
import AppError from "../../helper/AppError";
import {
  RegisterDTO,
  LoginDTO,
  UpdateProfileDTO,
  JwtPayload,
  UserRole,
} from "./user.types";

const JWT_SECRET = process.env.JWT_SECRET!;
const JWT_EXPIRES_IN = process.env.JWT_EXPIRES_IN!;
const BCRYPT_ROUNDS = 12;

// ─── Helpers ──────────────────────────────────────────────────────────────────

// Strip password before returning user object to any caller
const sanitizeUser = (user: User): Omit<User, "password"> => {
  const { password, ...safe } = user.toJSON ? user.toJSON() : (user as any);
  return safe;
};

const signToken = (payload: JwtPayload): string =>
  jwt.sign(payload, JWT_SECRET, { expiresIn: JWT_EXPIRES_IN } as jwt.SignOptions);

// Query email GSI — used both for duplicate check and login lookup
const findByEmail = async (email: string): Promise<User | null> => {
  const normalised = email.toLowerCase().trim();

  // Query on email-index GSI — O(1), not a Scan
  const results = await UserModel.query("email")
    .eq(normalised)
    .using("email-index")
    .limit(1)
    .exec();

  return results.count > 0 ? results[0] : null;
};

// ─────────────────────────────────────────────────────────────────────────────
// 1. REGISTER  →  Query (duplicate check) + PutItem
// ─────────────────────────────────────────────────────────────────────────────

const register = async (dto: RegisterDTO) => {
  // Step 1: check email uniqueness via GSI Query (cheap, not a Scan)
  const existing = await findByEmail(dto.email);
  if (existing) throw new AppError("Email already registered", 409);

  // Step 2: hash password — bcrypt with cost 12 (≈250ms, brute-force resistant)
  const hashedPassword = await bcrypt.hash(dto.password, BCRYPT_ROUNDS);

  // Step 3: create user — PutItem with UUID auto-generated by schema default
  const user = await UserModel.create({
    name: dto.name.trim(),
    email: dto.email,        
    password: hashedPassword,
    role: (dto.role as UserRole) || "user",
  });

  // Step 4: sign token with userId + email + role
  const token = signToken({
    userId: user.userId,
    email: user.email,
    role: user.role,
  });

  return { user: sanitizeUser(user), token };
};

// ─────────────────────────────────────────────────────────────────────────────
// 2. LOGIN  →  Query (email GSI) + bcrypt compare
// ─────────────────────────────────────────────────────────────────────────────

const login = async (dto: LoginDTO) => {
  // Step 1: find user by email via GSI Query (NOT a Scan)
  const user = await findByEmail(dto.email);

  // ⚠️  Security: use the SAME generic error for "not found" and "wrong password"
  //     to prevent email enumeration attacks
  if (!user) throw new AppError("Invalid email or password", 401);
  if (!user.isActive) throw new AppError("Account is deactivated", 403);

  // Step 2: compare plaintext password against bcrypt hash
  const isMatch = await bcrypt.compare(dto.password, user.password);
  if (!isMatch) throw new AppError("Invalid email or password", 401);

  const token = signToken({
    userId: user.userId,
    email: user.email,
    role: user.role,
  });

  return { user: sanitizeUser(user), token };
};

// ─────────────────────────────────────────────────────────────────────────────
// 3. GET PROFILE  →  GetItem (userId from JWT)
// ─────────────────────────────────────────────────────────────────────────────
// JWT payload already has userId — direct GetItem, no index needed.

const getProfile = async (userId: string) => {
  const user = await UserModel.get({ userId });
  if (!user) throw new AppError("User not found", 404);
  return sanitizeUser(user);
};

// ─────────────────────────────────────────────────────────────────────────────
// 4. UPDATE PROFILE  →  UpdateItem (partial, only provided fields written)
// ─────────────────────────────────────────────────────────────────────────────
// Uses UpdateItem — only the fields in `dto` are written to DynamoDB.
// The full item is NOT read and re-written (avoids race conditions).

const updateProfile = async (
  userId: string,
  dto: UpdateProfileDTO,
  file?: Express.Multer.File
): Promise<ReturnType<typeof sanitizeUser>> => {
  // If new avatar uploaded, handle S3 swap
  if (file) {
    // Fetch only to get the old avatar URL — we need it to delete from S3
    const existing = await UserModel.get({ userId });
    if (!existing) throw new AppError("User not found", 404);

    if (existing.avatar) {
      const oldKey = getS3KeyFromUrl(existing.avatar);
      const uploaded = await fileService.updateFromS3(oldKey, file);
      dto.avatar = uploaded.url;
    } else {
      const uploaded = await fileService.uploadToLocalStack(file);
      dto.avatar = uploaded.url;
    }
  }

  // UpdateItem — only writes the fields present in `dto`
  const updated = await UserModel.update({ userId }, dto);
  return sanitizeUser(updated);
};

// ─────────────────────────────────────────────────────────────────────────────
// 5. CHANGE PASSWORD  →  GetItem + bcrypt + UpdateItem
// ─────────────────────────────────────────────────────────────────────────────

const changePassword = async (
  userId: string,
  oldPassword: string,
  newPassword: string
) => {
  // GetItem to verify old password
  const user = await UserModel.get({ userId });
  if (!user) throw new AppError("User not found", 404);

  const isMatch = await bcrypt.compare(oldPassword, user.password);
  if (!isMatch) throw new AppError("Current password is incorrect", 401);

  const hashed = await bcrypt.hash(newPassword, BCRYPT_ROUNDS);

  // UpdateItem — only write the new password hash
  await UserModel.update({ userId }, { password: hashed });
};

// ─────────────────────────────────────────────────────────────────────────────
// 6. DELETE AVATAR  →  UpdateItem (REMOVE expression)
// ─────────────────────────────────────────────────────────────────────────────

const deleteAvatar = async (userId: string) => {
  const user = await UserModel.get({ userId });
  if (!user) throw new AppError("User not found", 404);

  if (user.avatar) {
    const key = getS3KeyFromUrl(user.avatar);
    await fileService.deleteFromS3(key);
    // REMOVE expression — deletes the attribute entirely from the DynamoDB item
    await UserModel.update({ userId }, { $REMOVE: { avatar: null } } as any);
  }
};

// ─────────────────────────────────────────────────────────────────────────────
export const userService = {
  register,
  login,
  getProfile,
  updateProfile,
  changePassword,
  deleteAvatar,
  findByEmail,
};